### ISSUE TITLE
Errors on empty css variables (boostrap 5.2)

### ISSUE THREAD

**Issue by it-xtech-dev** [failwyn/BundlerMinifier#14]
### Installed product versions
- Visual Studio: 2022
- This extension: 2.9.3

### Description
Empty css variables are treated as not allowed syntax while they are allowed in specs.

### Steps to recreate
1. Download https://github.com/twbs/bootstrap/releases/download/v5.2.2/bootstrap-5.2.2-dist.zip
2. Try to bundle: css.boostrap.css
3. Multiple errors Expected expression, found ';' will occur

### Current behavior
While processing empty value css variable an error is thrown.

### Expected behavior
Errors should not be thrown because empty css variables are proper syntax.

### Additional information
Issue seems to be fixed with nuglify https://github.com/trullock/NUglify/issues/331

**Comment by failwyn** [comment]
Thanks for this, I'll get a new version out as soon as I can with NUglify updated; a bit swamped at work at the moment, but I'll get it done.

**Comment by it-xtech-dev** [comment]
Great! I'm awaiting for new version to check whether problem is solved.

**Comment by failwyn** [comment]
@slavenl  The current version of WebCompiler is using NUglify 1.20.4, so this issue should be resolved; are you getting this exact error? Would you mind uploading a test project that shows the error that you are seeing?

**Comment by slavenl** [comment]
My setup: VS 2022 17.5.1
Extensions: 
Web compiler 2022+ (v.1.14.10)
Bundler & Minifier+ (v.2.9.3)

If minify{"enabled":false} - build passed OK
If minify{"enabled":true} - I got: (Bundler & Minifier) Expected expression, found ';' 

![image](https://user-images.githubusercontent.com/9960962/224316687-05a559e8-3d71-491a-a3a1-8f09925fc996.png)

![image](https://user-images.githubusercontent.com/9960962/224317317-0897efbc-f257-4d1e-bfdb-149d945f5fba.png)

![image](https://user-images.githubusercontent.com/9960962/224317434-c9826425-0a1d-4481-8d9f-2a5612ab9da2.png)

**Comment by failwyn** [comment]
Apologize, I mistook this issue as a WebCompiler issue; I’ll update NUglify in BundlerMinifier on Monday, test it for the week, and upload a new version on Friday; if you want to help test it, I can upload it here on Monday.

**Comment by slavenl** [comment]
I'll be glad to assist you in testing, if it's possible. Monday seems great.
Thank you for doing this.

**Comment by slavenl** [comment]
> Apologize, I mistook this issue as a WebCompiler issue; I’ll update NUglify in BundlerMinifier on Monday, test it for the week, and upload a new version on Friday; if you want to help test it, I can upload it here on Monday.

Any luck with updating NUglify?

**Comment by failwyn** [comment]
[BundlerMinifierVsix.zip](https://github.com/failwyn/BundlerMinifier/files/10968477/BundlerMinifierVsix.zip)
This version uses NUglify 1.20.5 and is arm64 compatible; let me know if you run into any issues, if everything looks good, I'll try to make the official release on Friday.

**Comment by slavenl** [comment]
Installed successfully as you can see on screenshot

![image](https://user-images.githubusercontent.com/9960962/225004531-34fdc478-c436-4910-82fc-fc7b03942bc1.png)

But unfortunately error stay persisted as on above screens

![image](https://user-images.githubusercontent.com/9960962/225005248-d7ae28c9-8cc8-41c9-bef9-d502e2f550c2.png)

As it seems, for now, bundler work OK, but minifier can't minify if css key dont have value.

**Comment by failwyn** [comment]
If you can make a minimal reproduction example, we could submit it to the NUglify repo and see if it can be fixed; When I get some time, I'll try fixing it and submitting a pull request.

**Comment by slavenl** [comment]
I created new project and recreated similar setup (with smaller number of css files to bundle) as in my original project and everything passed OK.  I'm really confused now. 
I'll try to find "catch" in next few days and If I manage that, I'll give you info where is the problem. 

Maybe it's everything OK with your extension but if you find time please upgrade WebCompiler + Bundler&Minifier in every case because people will need that. It's great component and please keep it alive.

For now, I can go with just bundled files. Thank you.

**Comment by failwyn** [comment]
Thanks! They are essential extensions for my company, so I’ll keep maintaining them until Visual Studio has good native support. I just get busy at work and don’t have time to be as responsive as I’d like with new versions.

**Comment by Lewis-Fam** [comment]
Hello. Thanks for managing this extension.  I am having the same issues as the OP.

I installed the 2.9.6 build you uploaded.  However, now it's throwing an exception.

Here is the error:

```
\users\daddy\appdata\local\microsoft\visualstudio\17.0_e4e2c58b\extensions\dmp2plwm.0xd\BundlerMinifierConsole.exe "wwwroot/css/site.bundle.min.css" "D:/daddy/dev/.alltdl/src/apps/web/terrelllewis.com/public/bundleconfig.json"
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at BundlerMinifier.BundleHandler.TryGetBundles(String configFile, IEnumerable`1& bundles)
   at BundlerMinifierConsole.Program.GetConfigFileFromArgs(String[] args, String& configPath)
   at BundlerMinifierConsole.Program.Main(String[] args)
Process terminated with code -532462766.
```

**Comment by Lewis-Fam** [comment]
> @slavenl - Try and bundle bootstrap? I've only have issues when I include bootstrap version 5.2 or 5.3.   

5.1 and 5.0 bundle fine.

**Comment by slavenl** [comment]
> > @slavenl
> 
> Try and bundle bootstrap? I've only had issues when I include bootstrap version 5.2 or 5.3.
> 
> 5.1 and 5.0 bundle fine.

Issue was born with bootstrap v5.2 because in that version bootstrap embrace emty/null values which seems a problem now. In project we use DevExtreme 22.1.4 which contain Bootstrap 5.2.3. so :)

**Comment by dserri** [comment]
Hello, is there any news on this topic? I have a project with the latest Bootstrap version and on Rebuild the bundler throws errors. fun fact: if i clean then build it works fine, but with rebuild this error occurs. Any idea why that could happen?

**Comment by failwyn** [comment]
I'll try to update bootstrap in my project this week and take a stab at fixing this.

**Comment by dserri** [comment]
> I'll try to update bootstrap in my project this week and take a stab at fixing this.

For better context, the bundler works when:

from Task Runner Explorer: update all files
from Build option on solution, even after a clean

Doesn't work when:

from Rebuild on solution
