### ISSUE TITLE
Create/update bundles fails with System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by amilo2003** [failwyn/BundlerMinifier#22]
### Installed product versions
- Visual Studio: 2022 17.5.5
- This extension: 2.9.9

### Description
Creating a new bundle fails when the solution is bound to source control, in this case Azure Devops.  

### Steps to recreate
1. Select 2 .js files
2. Right click, Bundle and minify files

### Current behavior
Creating a new bundle fails with dialog message below when the solution is bound to source control, in this case Azure Devops.  
---------------------------
Microsoft Visual Studio
---------------------------
Access to the path 'D:\Visual Studio\Test\Project\bundleconfig.json' is denied.
---------------------------
OK   
---------------------------

If a .min file already exists, the .min file is automatically checked out, but bundleconfig.json is not automatically checked out. 

If bundleconfig.json is checked out, creating a new bundle fails although the entries are created in bundleconfig.json. The target bundle is not created unless ALL bundles in bundleconfig.json are checked out for editing, even nothing when changed. Error message:

System.UnauthorizedAccessException: Access to the path 'D:\Visual Studio\Test\Project\wwwroot\js\custom-validation.min.js' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at BundlerMinifier.BundleFileProcessor.ProcessBundle(String baseFolder, Bundle bundle) in W:\Git\Light Speed Solutions\BundlerMinifier\src\BundlerMinifier.Core\Bundle\BundleFileProcessor.cs:line 140
   at BundlerMinifier.BundleFileProcessor.Process(String fileName, IEnumerable`1 bundles) in W:\Git\Light Speed Solutions\BundlerMinifier\src\BundlerMinifier.Core\Bundle\BundleFileProcessor.cs:line 40
   at BundlerMinifierVsix.BundleService.<>c__DisplayClass8_0.<Process>b__0(Object o) in W:\Git\Light Speed Solutions\BundlerMinifier\src\BundlerMinifierVsix\BundleService.cs:line 112

### Expected behavior
Necessary bundled files should be checked out automatically.

**Comment by amilo2003** [comment]
How does it work when an already minified file is edited? For example file.js is bundled and minified to file.min.js. When both are checked in and file.js is edited, VS automatically checks out the file. And the min.js file is also checked out.

It worked fine in previous versions of VS.

But the big issue is not the System.UnauthorizedAccessException, why are ALL bundled files minified when adding a new bundle even though no other source files changed?


________________________________

**Comment by amilo2003** [comment]
Same error. Somehow VS does not recognize the attempt to modify the .min files as triggered from the IDE and does not check the necessary files out. 

 

System.UnauthorizedAccessException: Access to the path 'D:\Visual Studio\Project\Solution\Web\wwwroot\js\lookup.min.js' is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)

   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)

   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)

   at BundlerMinifier.BundleFileProcessor.ProcessBundle(String baseFolder, Bundle bundle) in W:\Git\Light Speed Solutions\BundlerMinifier\src\BundlerMinifier.Core\Bundle\BundleFileProcessor.cs:line 140

   at BundlerMinifier.BundleFileProcessor.Process(String fileName, IEnumerable`1 bundles) in W:\Git\Light Speed Solutions\BundlerMinifier\src\BundlerMinifier.Core\Bundle\BundleFileProcessor.cs:line 40

   at BundlerMinifierVsix.BundleService.<>c__DisplayClass8_0.<Process>b__0(Object o) in W:\Git\Light Speed Solutions\BundlerMinifier\src\BundlerMinifierVsix\BundleService.cs:line 112
